# ./.tmuxinator.yml

name: evo-experiments
root: <%= ENV["PWD"] %>

windows:
  - backend:
      - cd backend/src && flask --app main run
  - frontend:
      - cd frontend && npm run dev
  - blank-term:
